/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.clothes;

import Business.NEUServeUp;
import Business.Work.Work;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rwalawalkar
 */
public class ClothesDashboard extends javax.swing.JPanel {

    public NEUServeUp neuServeUp;
    /**
     * Creates new form ClothesDashboard
     */
    public ClothesDashboard() {
        initComponents();
        neuServeUp = NEUServeUp.getInstance();
        populateWorkRequeststable();
    }
    
    public void populateWorkRequeststable(){
        DefaultTableModel dtm = (DefaultTableModel) tblWorkRequests.getModel();
        dtm.setRowCount(0);        
        for(Work work : neuServeUp.getWorkDirectory().getWorkList()){
            if(work.getFiduciaryClothesDecission()!= null && work.getFiduciaryClothesDecission().getFiduciaryClothesDecission().equalsIgnoreCase("APPROVED")){
                if(work.getClothesCostEstimate()== null || !work.getClothesCostEstimate().isIsClothesQuotationSent()){
                    Object[] row = new Object[dtm.getColumnCount()];
                    row[0]=work;
                    row[1]= work.getClothesWorkRequest().getNumberOfLargePants();
                    row[2]= work.getClothesWorkRequest().getNumberOfMediumPants();
                    row[3]= work.getClothesWorkRequest().getNumberOfSmallPants();
                    row[4]= work.getClothesWorkRequest().getNumberOfLargeShirts();
                    row[5]= work.getClothesWorkRequest().getNumberOfMediumShirts();
                    row[6]= work.getClothesWorkRequest().getNumberOfSmallShirts();
                    dtm.addRow(row);
                }
            }
        }
        populatePastWorkRequeststable();
    }   
    
    public void populatePastWorkRequeststable(){
        DefaultTableModel dtm = (DefaultTableModel) tblPastWorkRequests.getModel();
        dtm.setRowCount(0);        
        for(Work work : neuServeUp.getWorkDirectory().getWorkListLastestFirstOrder()){
            if(work.getFiduciaryClothesDecission()!= null && work.getFiduciaryClothesDecission().getFiduciaryClothesDecission().equalsIgnoreCase("APPROVED")){
                if(work.getClothesCostEstimate()!= null && work.getClothesCostEstimate().isIsClothesQuotationSent()){
                    Object[] row = new Object[dtm.getColumnCount()];
                    row[0]=work;
                    row[1]= work.getAegisApprovalStatusClothes();
                    dtm.addRow(row);
                }
            }
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPastWorkRequests = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblWorkRequests = new javax.swing.JTable();
        btnViewWork = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(38, 54, 68));

        jLabel3.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(148, 150, 149));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("CLOTHES AID");

        tblPastWorkRequests.setBackground(new java.awt.Color(255, 255, 255));
        tblPastWorkRequests.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        tblPastWorkRequests.setFont(new java.awt.Font("Monaco", 0, 12)); // NOI18N
        tblPastWorkRequests.setForeground(new java.awt.Color(83, 81, 85));
        tblPastWorkRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Work ID", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPastWorkRequests.setGridColor(new java.awt.Color(83, 81, 85));
        tblPastWorkRequests.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tblPastWorkRequests);

        tblWorkRequests.setBackground(new java.awt.Color(255, 255, 255));
        tblWorkRequests.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        tblWorkRequests.setFont(new java.awt.Font("Monaco", 0, 12)); // NOI18N
        tblWorkRequests.setForeground(new java.awt.Color(83, 81, 85));
        tblWorkRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Work ID", "Pants Large", "Pants Medium", "Pants Small", "Shirts Large", "Shirts Medium", "Shirts Small"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWorkRequests.setGridColor(new java.awt.Color(83, 81, 85));
        tblWorkRequests.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane2.setViewportView(tblWorkRequests);
        if (tblWorkRequests.getColumnModel().getColumnCount() > 0) {
            tblWorkRequests.getColumnModel().getColumn(0).setResizable(false);
            tblWorkRequests.getColumnModel().getColumn(1).setResizable(false);
            tblWorkRequests.getColumnModel().getColumn(2).setResizable(false);
            tblWorkRequests.getColumnModel().getColumn(3).setResizable(false);
            tblWorkRequests.getColumnModel().getColumn(4).setResizable(false);
            tblWorkRequests.getColumnModel().getColumn(5).setResizable(false);
            tblWorkRequests.getColumnModel().getColumn(6).setResizable(false);
        }

        btnViewWork.setBackground(new java.awt.Color(255, 255, 255));
        btnViewWork.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnViewWork.setForeground(new java.awt.Color(83, 81, 85));
        btnViewWork.setText("View");
        btnViewWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewWorkActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(148, 150, 149));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("New Work Request");

        jLabel5.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(148, 150, 149));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Past Work Requests");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewWork, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnViewWork)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewWorkActionPerformed
        // TODO add your handling code here:

        if(tblWorkRequests.getSelectedRow() >= 0){
            Work work = (Work) tblWorkRequests.getValueAt(tblWorkRequests.getSelectedRow(),0);
            ClothesWorkEstimate clothesWorkEstimate= new ClothesWorkEstimate(work);
            neuServeUp.getPanelBody().add("ClothesWorkEstimate", clothesWorkEstimate);
            CardLayout layout = (CardLayout) neuServeUp.getPanelBody().getLayout();
            layout.next(neuServeUp.getPanelBody());
        }else{
            JOptionPane.showMessageDialog(null, "Please select a work");
        }
    }//GEN-LAST:event_btnViewWorkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewWork;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPastWorkRequests;
    private javax.swing.JTable tblWorkRequests;
    // End of variables declaration//GEN-END:variables
}
