/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.DB4OUtil.DB4ONUtil;
import Business.NEUServeUp;
import Business.NUserAccount.NUser;
import java.awt.CardLayout;
import userinterface.admin.AdminDashboard;
import userinterface.aegis.AegisDashboard;
import userinterface.clothes.ClothesDashboard;
import userinterface.fiduciary.FiduciaryDashboard;
import userinterface.medical.MedicalDashboard;
import userinterface.survey.SurveyDashboard;

/**
 *
 * @author Aishwarya
 */
public class MainFrame extends javax.swing.JFrame {

    private NEUServeUp system;
    private DB4ONUtil dB4ONUtil = DB4ONUtil.getInstance();
    public MainFrame() {
        initComponents();
        system = dB4ONUtil.retrieveSystem();
        setLogoutButton(false);
        system.setPanelBody(panelBody);
        system.setbtnLogout(btnLogout);
        system.setbtnProfile(btnProfile);
        navigateToLoginLayout();
    }
    
    public void setLogoutButton(boolean flag){
        btnLogout.setVisible(flag);
        btnProfile.setVisible(flag);
    }
    
    public void navigateToLoginLayout(){
        LoginLayout loginLayout = new LoginLayout();
        panelBody.add("LoginLayout", loginLayout);
        CardLayout layout = (CardLayout) panelBody.getLayout();
        layout.next(panelBody);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSplitPanel = new javax.swing.JSplitPane();
        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        panelBody = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainSplitPanel.setDividerSize(1);
        mainSplitPanel.setForeground(new java.awt.Color(60, 63, 65));
        mainSplitPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        panelHeader.setPreferredSize(new java.awt.Dimension(1000, 100));

        jLabel1.setFont(new java.awt.Font("Monaco", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(249, 6, 6));
        jLabel1.setText("NEU:ServeUp");

        jLabel2.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(83, 81, 85));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("By Dread-Nought");

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnHome.setForeground(new java.awt.Color(83, 81, 85));
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(83, 81, 85));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnProfile.setBackground(new java.awt.Color(255, 255, 255));
        btnProfile.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(83, 81, 85));
        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 428, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHome)
                            .addComponent(btnLogout)
                            .addComponent(btnProfile)))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        mainSplitPanel.setTopComponent(panelHeader);

        panelBody.setBackground(new java.awt.Color(38, 54, 68));
        panelBody.setPreferredSize(new java.awt.Dimension(1000, 600));
        panelBody.setLayout(new java.awt.CardLayout());

        jLabel4.setFont(new java.awt.Font("Monaco", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(148, 150, 149));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("WELCOME!");
        panelBody.add(jLabel4, "card3");

        mainSplitPanel.setRightComponent(panelBody);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainSplitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        NUser nUser = system.getuUser(); 
        if(nUser != null){
            if(nUser.getnOrganization().getnOrganizationType().getValue().equals("Survey")){
                SurveyDashboard surveyDashboard= new SurveyDashboard();
                panelBody.add("SurveyDashboard", surveyDashboard);
                CardLayout layout = (CardLayout) panelBody.getLayout();
                layout.next(panelBody);
            } else if(nUser.getnOrganization().getnOrganizationType().getValue().equals("Fiduciary")){
                FiduciaryDashboard fiduciaryDashboard= new FiduciaryDashboard();
                panelBody.add("FiduciaryDashboard", fiduciaryDashboard);
                CardLayout layout = (CardLayout) panelBody.getLayout();
                layout.next(panelBody);
            } else if(nUser.getnOrganization().getnOrganizationType().getValue().equals("Aegis")){
                AegisDashboard aegisDashboard= new AegisDashboard();
                panelBody.add("AegisDashboard", aegisDashboard);
                CardLayout layout = (CardLayout) panelBody.getLayout();
                layout.next(panelBody);
            }else if(nUser.getnOrganization().getnOrganizationType().getValue().equals("MedicalAid")){
                MedicalDashboard medicalDashboard= new MedicalDashboard();
                panelBody.add("MedicalDashboard", medicalDashboard);
                CardLayout layout = (CardLayout) panelBody.getLayout();
                layout.next(panelBody);
            } else if(nUser.getnOrganization().getnOrganizationType().getValue().equals("ClothesAid")){
                ClothesDashboard clothesDashboard= new ClothesDashboard();
                panelBody.add("ClothesDashboard", clothesDashboard);
                CardLayout layout = (CardLayout) panelBody.getLayout();
                layout.next(panelBody);
            } else if(nUser.getnOrganization().getnOrganizationType().getValue().equals("Admin")){
                AdminDashboard adminDashboard= new AdminDashboard();
                panelBody.add("AdminDashboard", adminDashboard);
                CardLayout layout = (CardLayout) panelBody.getLayout();
                layout.next(panelBody);
            } else {
                LoginLayout loginLayout = new LoginLayout();
                panelBody.add("LoginLayout", loginLayout);
                CardLayout layout = (CardLayout) panelBody.getLayout();
                layout.next(panelBody);
            }
        }
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        system.setuUser(null);
        navigateToLoginLayout();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:                
        UpdatePasswordJPanel updatePasswordJPanel= new UpdatePasswordJPanel();
        panelBody.add("UpdatePasswordJPanel", updatePasswordJPanel);
        CardLayout layout = (CardLayout) panelBody.getLayout();
        layout.next(panelBody);
    }//GEN-LAST:event_btnProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSplitPane mainSplitPanel;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelHeader;
    // End of variables declaration//GEN-END:variables
}
