/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.NEUServeUp;
import javax.swing.JOptionPane;
import Business.Util.Helper;
import java.awt.CardLayout;
import java.awt.Component;
import userinterface.aegis.AegisDashboard;
import Business.NUserAccount.NUser;
import Business.NUserAccount.NUserDirectory;
import userinterface.admin.AdminDashboard;
import userinterface.clothes.ClothesDashboard;
import userinterface.fiduciary.FiduciaryDashboard;
import userinterface.medical.MedicalDashboard;
import userinterface.survey.SurveyDashboard;
/**
 *
 * @author Lenovo
 */
public class UpdatePasswordJPanel extends javax.swing.JPanel {
public Helper helper;
 public NEUServeUp neuServeUp;
    /**
     * Creates new form UpdatePasswordJPanel
     */
    NUser nUser;
    public UpdatePasswordJPanel() {
        initComponents();
        neuServeUp = NEUServeUp.getInstance();
        this.nUser  = neuServeUp.getuUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtFieldPasswordNew = new javax.swing.JTextField();
        txtFieldPasswordConfirm = new javax.swing.JTextField();

        setBackground(new java.awt.Color(38, 54, 68));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel2.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(148, 150, 149));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("New Password:");

        jLabel3.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(148, 150, 149));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("UPDATE PASSWORD");

        jLabel4.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(148, 150, 149));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Confirm Password:");

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnSave.setForeground(new java.awt.Color(83, 81, 85));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(83, 81, 85));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtFieldPasswordNew.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        txtFieldPasswordNew.setForeground(new java.awt.Color(83, 81, 85));
        txtFieldPasswordNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPasswordNewActionPerformed(evt);
            }
        });

        txtFieldPasswordConfirm.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        txtFieldPasswordConfirm.setForeground(new java.awt.Color(83, 81, 85));
        txtFieldPasswordConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPasswordConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldPasswordNew)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldPasswordConfirm))
                .addContainerGap(616, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFieldPasswordNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFieldPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnBack))
                .addContainerGap(356, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

     public void toPreviousScreen(){
        CardLayout layout = (CardLayout) this.neuServeUp.getPanelBody().getLayout();
        neuServeUp.getPanelBody().remove(this);
        Component[] comps =  neuServeUp.getPanelBody().getComponents();
        layout.previous(neuServeUp.getPanelBody());
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    
        
        if(txtFieldPasswordNew.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter valid password");
            return;
        }
//        if(!helper.isValidString(txtFieldPasswordConfirm.getText())){
//            JOptionPane.showMessageDialog(null, "Please enter password");
//            return;
//        }
        if (!txtFieldPasswordConfirm.getText().equals(txtFieldPasswordNew.getText())){
            JOptionPane.showMessageDialog(null,"Password does not match");
            return;
        }
       
          NUserDirectory nUserDirectory = NEUServeUp.getInstance().getUserDirectory();
        neuServeUp.getUserDirectory().userUpdate(nUser.getuEmail(), txtFieldPasswordConfirm.getText());
        JOptionPane.showMessageDialog(null,"Password updated successfully");
        toPreviousScreen();
   
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        toPreviousScreen();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtFieldPasswordNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPasswordNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPasswordNewActionPerformed

    private void txtFieldPasswordConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPasswordConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPasswordConfirmActionPerformed
  
                         

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFieldPasswordConfirm;
    private javax.swing.JTextField txtFieldPasswordNew;
    // End of variables declaration//GEN-END:variables
}
