/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.aegis;

import Business.NEUServeUp;
import Business.Work.Work;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author rwalawalkar
 */
public class AegisWorkDecision extends javax.swing.JPanel {

    private Work work;
    public NEUServeUp neuServeUp;
    /**
     * Creates new form AegisWorkDecision
     */
    public AegisWorkDecision(Work work) {
        initComponents();
        this.work = work;
        neuServeUp = NEUServeUp.getInstance();
        setValuesInFields();
    }
    
    public void setValuesInFields(){
        textFieldNoOfPeople.setText(work.getNumberOfPeople()+"");
        textWorkID.setText(work.getWorkId()+"");
        
        textFieldClothesEstimate.setText(work.getTotalClothesEstimatedCost()+"");
        textFieldClothesStatus.setText(work.getAegisApprovalStatusClothes());
        
        textFieldMedicalStatus.setText(work.getAegisApprovalStatusMed());
        textMedicalEstimate.setText(work.getTotalMedicalEstimatedCost()+"");
        
        if(work.getAegisApprovalStatusMed().equalsIgnoreCase("PENDING")){
            setMedicalButtons(true);
        }else {
            setMedicalButtons(false);
        }
        if(work.getAegisApprovalStatusClothes().equalsIgnoreCase("PENDING")){
            setClothesButtons(true);
        }else {
            setClothesButtons(false);
        }
    }
    
    public void setMedicalButtons(boolean flag){
        btnMedApprove.setEnabled(flag);
        btnMedReject.setEnabled(flag);
    }
    
    public void setClothesButtons(boolean flag){
        btnClothesApprove.setEnabled(flag);
        btnClothesReject.setEnabled(flag);
    }
    
    public void toPreviousScreen(){
        CardLayout layout = (CardLayout) this.neuServeUp.getPanelBody().getLayout();
        neuServeUp.getPanelBody().remove(this);
        Component[] comps =  neuServeUp.getPanelBody().getComponents();
        for(Component comp:comps){
            if(comp instanceof AegisDashboard){
                AegisDashboard panel = (AegisDashboard)comp;
                panel.populateWorkRequeststable();
            }
        }
        layout.previous(neuServeUp.getPanelBody());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnMedApprove = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textFieldMedicalStatus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        textMedicalEstimate = new javax.swing.JTextField();
        btnMedReject = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        textWorkID = new javax.swing.JTextField();
        textFieldNoOfPeople = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textFieldClothesStatus = new javax.swing.JTextField();
        textFieldClothesEstimate = new javax.swing.JTextField();
        btnClothesApprove = new javax.swing.JButton();
        btnClothesReject = new javax.swing.JButton();

        setBackground(new java.awt.Color(38, 54, 68));
        setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(148, 150, 149));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Medicine");

        jLabel3.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(148, 150, 149));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("WORK STATUS");

        btnMedApprove.setBackground(new java.awt.Color(255, 255, 255));
        btnMedApprove.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnMedApprove.setForeground(new java.awt.Color(83, 81, 85));
        btnMedApprove.setText("Accept");
        btnMedApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedApproveActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(148, 150, 149));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Estimate:");

        textFieldMedicalStatus.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldMedicalStatus.setForeground(new java.awt.Color(83, 81, 85));
        textFieldMedicalStatus.setEnabled(false);
        textFieldMedicalStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMedicalStatusActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(148, 150, 149));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Status:");

        jLabel14.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(148, 150, 149));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Clothes List:");

        jLabel16.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(148, 150, 149));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("No. of People:");

        textMedicalEstimate.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textMedicalEstimate.setForeground(new java.awt.Color(83, 81, 85));
        textMedicalEstimate.setEnabled(false);
        textMedicalEstimate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMedicalEstimateActionPerformed(evt);
            }
        });

        btnMedReject.setBackground(new java.awt.Color(255, 255, 255));
        btnMedReject.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnMedReject.setForeground(new java.awt.Color(83, 81, 85));
        btnMedReject.setText("Reject");
        btnMedReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedRejectActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(83, 81, 85));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(148, 150, 149));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Work ID:");

        textWorkID.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textWorkID.setForeground(new java.awt.Color(83, 81, 85));
        textWorkID.setEnabled(false);
        textWorkID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textWorkIDActionPerformed(evt);
            }
        });

        textFieldNoOfPeople.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfPeople.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfPeople.setEnabled(false);
        textFieldNoOfPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfPeopleActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(148, 150, 149));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Estimate:");

        jLabel11.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(148, 150, 149));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Status:");

        textFieldClothesStatus.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldClothesStatus.setForeground(new java.awt.Color(83, 81, 85));
        textFieldClothesStatus.setEnabled(false);
        textFieldClothesStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldClothesStatusActionPerformed(evt);
            }
        });

        textFieldClothesEstimate.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldClothesEstimate.setForeground(new java.awt.Color(83, 81, 85));
        textFieldClothesEstimate.setEnabled(false);
        textFieldClothesEstimate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldClothesEstimateActionPerformed(evt);
            }
        });

        btnClothesApprove.setBackground(new java.awt.Color(255, 255, 255));
        btnClothesApprove.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnClothesApprove.setForeground(new java.awt.Color(83, 81, 85));
        btnClothesApprove.setText("Accept");
        btnClothesApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClothesApproveActionPerformed(evt);
            }
        });

        btnClothesReject.setBackground(new java.awt.Color(255, 255, 255));
        btnClothesReject.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnClothesReject.setForeground(new java.awt.Color(83, 81, 85));
        btnClothesReject.setText("Reject");
        btnClothesReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClothesRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldNoOfPeople, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textWorkID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(208, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textMedicalEstimate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMedApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(textFieldMedicalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMedReject, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textFieldClothesEstimate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(textFieldClothesStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnClothesApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClothesReject, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19)
                    .addComponent(textWorkID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNoOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textMedicalEstimate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMedApprove))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldMedicalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(btnMedReject))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textFieldClothesEstimate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClothesApprove))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldClothesStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnClothesReject)))
                .addGap(129, 129, 129)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedApproveActionPerformed
        // TODO add your handling code here:
        work.setAegisMedicalDecision(neuServeUp.getuUser(),true);
        setValuesInFields();
        JOptionPane.showMessageDialog(null, "Response recorded");
    }//GEN-LAST:event_btnMedApproveActionPerformed

    private void textFieldMedicalStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMedicalStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldMedicalStatusActionPerformed

    private void textMedicalEstimateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMedicalEstimateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMedicalEstimateActionPerformed

    private void btnMedRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedRejectActionPerformed
        // TODO add your handling code here:
        work.setAegisMedicalDecision(neuServeUp.getuUser(),false);
        setValuesInFields();
        JOptionPane.showMessageDialog(null, "Response recorded");
    }//GEN-LAST:event_btnMedRejectActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        toPreviousScreen();
    }//GEN-LAST:event_btnBackActionPerformed

    private void textWorkIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textWorkIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textWorkIDActionPerformed

    private void textFieldNoOfPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfPeopleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfPeopleActionPerformed

    private void textFieldClothesStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldClothesStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldClothesStatusActionPerformed

    private void textFieldClothesEstimateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldClothesEstimateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldClothesEstimateActionPerformed

    private void btnClothesApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClothesApproveActionPerformed
        // TODO add your handling code here:
        work.setAegisClothesDecision(neuServeUp.getuUser(),true);
        setValuesInFields();
        JOptionPane.showMessageDialog(null, "Response recorded");
        
    }//GEN-LAST:event_btnClothesApproveActionPerformed

    private void btnClothesRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClothesRejectActionPerformed
        // TODO add your handling code here:
        work.setAegisClothesDecision(neuServeUp.getuUser(),false);
        setValuesInFields();
        JOptionPane.showMessageDialog(null, "Response recorded");
    }//GEN-LAST:event_btnClothesRejectActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClothesApprove;
    private javax.swing.JButton btnClothesReject;
    private javax.swing.JButton btnMedApprove;
    private javax.swing.JButton btnMedReject;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField textFieldClothesEstimate;
    private javax.swing.JTextField textFieldClothesStatus;
    private javax.swing.JTextField textFieldMedicalStatus;
    private javax.swing.JTextField textFieldNoOfPeople;
    private javax.swing.JTextField textMedicalEstimate;
    private javax.swing.JTextField textWorkID;
    // End of variables declaration//GEN-END:variables
}
