/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.aegis;

import Business.NEUServeUp;
import Business.Util.Helper;
import Business.Work.Work;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rwalawalkar
 */
public class AegisDashboard extends javax.swing.JPanel {

    public NEUServeUp neuServeUp;
    /**
     * Creates new form AegisDashboard
     */
    public AegisDashboard() {
        initComponents();
        neuServeUp = NEUServeUp.getInstance();
        populateWorkRequeststable();
    }
    
    public void populateWorkRequeststable(){
        DefaultTableModel dtm = (DefaultTableModel) tblWorkRequests.getModel();
        dtm.setRowCount(0);
        
        for(Work work : neuServeUp.getWorkDirectory().getWorkListLastestFirstOrder()){
            if(work.getClothesCostEstimate()!= null && work.getClothesCostEstimate().isIsClothesQuotationSent() || work.getMedicalCostEstimate() != null && work.getMedicalCostEstimate().isIsMedQuotationSent()){
                Object[] row = new Object[dtm.getColumnCount()];
                row[0]=work;
                row[1]= getTotalCost(work);
                row[2]= getStatusOfBothInventory(work);
                dtm.addRow(row);
            }
        }
    }
    
    public String getTotalCost(Work work){
        String message = "";
        message = "Medical: "+work.getTotalMedicalEstimatedCost()+ " \nClothes: "+ work.getTotalClothesEstimatedCost();
        return message;
    }
    
    public String getStatusOfBothInventory(Work work){
        String message = "";
        message = "Medical: "+ work.getAegisApprovalStatusMed()
                + " \nClothes: "+ work.getAegisApprovalStatusClothes();
        return message;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequests = new javax.swing.JTable();

        setBackground(new java.awt.Color(38, 54, 68));

        jLabel3.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(148, 150, 149));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("AEGIS");

        btnView.setBackground(new java.awt.Color(255, 255, 255));
        btnView.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnView.setForeground(new java.awt.Color(83, 81, 85));
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        tblWorkRequests.setBackground(new java.awt.Color(255, 255, 255));
        tblWorkRequests.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        tblWorkRequests.setFont(new java.awt.Font("Monaco", 0, 12)); // NOI18N
        tblWorkRequests.setForeground(new java.awt.Color(83, 81, 85));
        tblWorkRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Work ID", "Cost Estimate", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWorkRequests.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tblWorkRequests);
        if (tblWorkRequests.getColumnModel().getColumnCount() > 0) {
            tblWorkRequests.getColumnModel().getColumn(0).setResizable(false);
            tblWorkRequests.getColumnModel().getColumn(1).setResizable(false);
            tblWorkRequests.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnView)
                .addContainerGap(74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        if(tblWorkRequests.getSelectedRow() >= 0){
            Work work = (Work) tblWorkRequests.getValueAt(tblWorkRequests.getSelectedRow(),0);
            AegisWorkDecision clothesWorkEstimate= new AegisWorkDecision(work);
            neuServeUp.getPanelBody().add("AegisWorkDecision", clothesWorkEstimate);
            CardLayout layout = (CardLayout) neuServeUp.getPanelBody().getLayout();
            layout.next(neuServeUp.getPanelBody());
        }else{
            JOptionPane.showMessageDialog(null, "Please select a work");
        }
    }//GEN-LAST:event_btnViewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblWorkRequests;
    // End of variables declaration//GEN-END:variables
}
