/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.admin;

import Business.NEUServeUp;
import Business.NEnterprise.NEnterprise;
import Business.NEnterprise.NEnterprise.NEnterpriseType;
import Business.NOrganization.NOrganization.NOrganizationType;
import Business.NEnterprise.NEnterpriseDirectory;
import Business.NOrganization.NOrganization;
import Business.NUserAccount.NUser;
import Business.NUserAccount.NUserDirectory;
import Business.NOrganization.NOrganization;
import Business.Util.Helper;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import userinterface.survey.SurveyDashboard;

/**
 *
 * @author Aishwarya
 */
public class CreateUserLogin extends javax.swing.JPanel {

    NEUServeUp neuServeUp;
    ArrayList<NOrganization> nEnterpriseOrganization;
    
    /**
     * Creates new form CreateUserLogin
     */
    public CreateUserLogin() {
        initComponents();
        neuServeUp =  NEUServeUp.getInstance();
        populateECombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxOrganization = new javax.swing.JComboBox();
        comboBoxEnterprise = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        btnLogin2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        textFieldPassword = new javax.swing.JTextField();
        textFieldConfirmPassword = new javax.swing.JTextField();

        setBackground(new java.awt.Color(38, 54, 68));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(83, 81, 85));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(148, 150, 149));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("CREATE USER");

        jLabel2.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(148, 150, 149));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Enterprise:");

        jLabel4.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(148, 150, 149));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Organization:");

        comboBoxOrganization.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        comboBoxOrganization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        comboBoxEnterprise.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        comboBoxEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEnterpriseActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(148, 150, 149));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Password");

        jLabel7.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(148, 150, 149));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Confirm Password:");

        textFieldEmail.setForeground(new java.awt.Color(83, 81, 85));
        textFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEmailActionPerformed(evt);
            }
        });

        btnLogin2.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin2.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnLogin2.setForeground(new java.awt.Color(83, 81, 85));
        btnLogin2.setText("Create User");
        btnLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(148, 150, 149));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Email:");

        textFieldPassword.setForeground(new java.awt.Color(83, 81, 85));
        textFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPasswordActionPerformed(evt);
            }
        });

        textFieldConfirmPassword.setForeground(new java.awt.Color(83, 81, 85));
        textFieldConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldConfirmPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldConfirmPassword)
                            .addComponent(textFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(comboBoxEnterprise, 0, 162, Short.MAX_VALUE)
                            .addComponent(comboBoxOrganization, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnLogin2))
                .addContainerGap(259, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        toPreviousScreen();
    }//GEN-LAST:event_btnBackActionPerformed

    private void textFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEmailActionPerformed

    private void btnLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin2ActionPerformed
        // TODO add your handling code here:
        Helper helper = new Helper();
        if (textFieldEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the email ID");
            return;
        }
        if (!helper.isValidEmail(textFieldEmail.getText())) {
            JOptionPane.showMessageDialog(null, "Please enter valid email ID");
            return;
        }
       
        if (textFieldPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the password");
            return;
        }
       
        if (textFieldConfirmPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please re-enter the password for confirmation");
            return;
        }
        
        if(!textFieldConfirmPassword.getText().equals(textFieldPassword.getText())){
            JOptionPane.showMessageDialog(null, "Re-enter same password for confirmation");
            return;
        }
        if(neuServeUp.getUserDirectory().checkIfUserIsDeleted(textFieldEmail.getText()))
        {
            JOptionPane.showMessageDialog(null, "User was previously deleted, can't create this user.");
            return;
        }
        if(neuServeUp.getUserDirectory().checkIfUserExists(textFieldEmail.getText()))
        {
            JOptionPane.showMessageDialog(null, "User already registered");
            return;
        }
        
        neuServeUp.getUserDirectory().userCreation(textFieldEmail.getText(),
                textFieldEmail.getText(), 
                textFieldPassword.getText(), 
                nEnterpriseOrganization.get(comboBoxOrganization.getSelectedIndex())
        );
        JOptionPane.showMessageDialog(null, "User created successfully for organisation " + comboBoxOrganization.getSelectedItem().toString());
        toPreviousScreen();
    }//GEN-LAST:event_btnLogin2ActionPerformed

    private void comboBoxEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEnterpriseActionPerformed
        // TODO add your handling code here:

        populateOrgCombo();
    }//GEN-LAST:event_comboBoxEnterpriseActionPerformed

    private void textFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPasswordActionPerformed

    private void textFieldConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldConfirmPasswordActionPerformed

    private void populateECombo() {
        comboBoxEnterprise.removeAllItems();
        for (NEnterprise nEnterprise : neuServeUp.getnEnterpriseDirectory().getNEnterpriseList()) {
            comboBoxEnterprise.addItem(nEnterprise);
        }
    }

     private void populateOrgCombo() {
        System.out.println(comboBoxEnterprise.getSelectedItem());
        nEnterpriseOrganization = neuServeUp.getnEnterpriseDirectory().getEnterpriseOrganizationList(comboBoxEnterprise.getSelectedItem().toString());
        comboBoxOrganization.removeAllItems();
        for (NOrganization nOrganization : nEnterpriseOrganization) {
            comboBoxOrganization.addItem(nOrganization.getnOrganizationType());
        }
    }

    public void toPreviousScreen() {
        NEUServeUp neuServeUp = NEUServeUp.getInstance();
        CardLayout layout = (CardLayout) neuServeUp.getPanelBody().getLayout();
        neuServeUp.getPanelBody().remove(this);
        Component[] comps = neuServeUp.getPanelBody().getComponents();
        for (Component comp : comps) {
            if (comp instanceof AdminDashboard) {
                AdminDashboard panel = (AdminDashboard) comp;
                panel.populateAdminTable();
            }
        }
        layout.previous(neuServeUp.getPanelBody());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin2;
    private javax.swing.JComboBox comboBoxEnterprise;
    private javax.swing.JComboBox comboBoxOrganization;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField textFieldConfirmPassword;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldPassword;
    // End of variables declaration//GEN-END:variables
}
