/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.fiduciary;

import Business.NEUServeUp;
import Business.Util.Helper;
import Business.Work.Work;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author rwalawalkar
 */
public class FiduciaryWorkDecission extends javax.swing.JPanel {
    
    private Work work;
    public NEUServeUp neuServeUp;

    /**
     * Creates new form FiduciaryWorkDecission
     */
    public FiduciaryWorkDecission(Work work) {
        initComponents();
        this.work = work;
        neuServeUp = NEUServeUp.getInstance();
        setValuesInFields();
        setDefaultButton();
    }
    
    public void setValuesInFields(){
        textFieldNoOfPeople.setText(work.getNumberOfPeople()+"");
        textWorkID.setText(work.getWorkId()+"");
        
        textFieldNoOfAnalgesics.setText(work.getMedicalWorkRequest().getNumberOfAnalgesics()+"");
        textFieldNoOfAntibiotics.setText(work.getMedicalWorkRequest().getNumberOfAntibiotics()+"");
        textFieldNoOfAntiflue.setText(work.getMedicalWorkRequest().getNumberOfAntiFlue()+"");
        textFieldNoOfAntipyretics.setText(work.getMedicalWorkRequest().getNumberOfAntipyretics()+"");
        textFieldNoOfAntiseptics.setText(work.getMedicalWorkRequest().getNumberOfAntiseptics()+"");
        
        textFieldNoOfPantsL.setText(work.getClothesWorkRequest().getNumberOfLargePants()+"");
        textFieldNoOfPantsM.setText(work.getClothesWorkRequest().getNumberOfMediumPants()+"");
        textFieldNoOfPantsS.setText(work.getClothesWorkRequest().getNumberOfSmallPants()+"");
        textFieldNoOfShirtsS.setText(work.getClothesWorkRequest().getNumberOfSmallShirts()+"");
        textFieldNoOfShirtsM.setText(work.getClothesWorkRequest().getNumberOfMediumShirts()+"");
        textFieldNoOfShirtsL.setText(work.getClothesWorkRequest().getNumberOfLargeShirts()+"");
        
        if(work.getFiduciaryMedicalDecission() != null){
            textMedResponseText.setText(work.getFiduciaryMedicalDecission().getFiduciaryMedicalDecission());
        }else{
            textMedResponseText.setText("PENDING");
        }
        
        if(work.getFiduciaryClothesDecission() != null){
            textClothesResponseText.setText(work.getFiduciaryClothesDecission().getFiduciaryClothesDecission());
        }else{
            textClothesResponseText.setText("PENDING");
        }
        
    }
    
    public void setDefaultButton(){
        if(work.getFiduciaryClothesDecission() == null){
            setClothesButtons(true);
        }else{
            setClothesButtons(false);
        }
        if(work.getFiduciaryMedicalDecission()== null){
            setMedicalButtons(true);
        }else{
            setMedicalButtons(false);
        }
    }
    
    public void setMedicalButtons(boolean flag){
        btnMedApprove.setEnabled(flag);
        btnMedReject.setEnabled(flag);
    }
    
    public void setClothesButtons(boolean flag){
        btnClothesApprove.setEnabled(flag);
        btnClothesReject.setEnabled(flag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldNoOfAnalgesics = new javax.swing.JTextField();
        btnMedApprove = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textFieldNoOfAntiflue = new javax.swing.JTextField();
        textMedResponseText = new javax.swing.JTextField();
        textFieldNoOfAntibiotics = new javax.swing.JTextField();
        textFieldNoOfAntiseptics = new javax.swing.JTextField();
        textFieldNoOfShirtsL = new javax.swing.JTextField();
        textFieldNoOfShirtsS = new javax.swing.JTextField();
        textFieldNoOfPantsS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textFieldNoOfPantsM = new javax.swing.JTextField();
        textFieldNoOfShirtsM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        textFieldNoOfPantsL = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textFieldNoOfAntipyretics = new javax.swing.JTextField();
        btnMedReject = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnClothesApprove = new javax.swing.JButton();
        btnClothesReject = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        textWorkID = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        textFieldNoOfPeople = new javax.swing.JTextField();
        textClothesResponseText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(38, 54, 68));

        jLabel2.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(148, 150, 149));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Medicine List:");

        jLabel3.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(148, 150, 149));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("WORK PROFILE");

        jLabel4.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(148, 150, 149));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("No. of Antiflue:");

        textFieldNoOfAnalgesics.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfAnalgesics.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfAnalgesics.setEnabled(false);
        textFieldNoOfAnalgesics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfAnalgesicsActionPerformed(evt);
            }
        });

        btnMedApprove.setBackground(new java.awt.Color(255, 255, 255));
        btnMedApprove.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnMedApprove.setForeground(new java.awt.Color(83, 81, 85));
        btnMedApprove.setText("Accept");
        btnMedApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedApproveActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(148, 150, 149));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("No. of Antipyretics:");

        jLabel6.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(148, 150, 149));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("No. of Analgesics:");

        jLabel7.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(148, 150, 149));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("No. of Antibiotics:");

        jLabel8.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(148, 150, 149));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("No. of Antiseptics:");

        textFieldNoOfAntiflue.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfAntiflue.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfAntiflue.setEnabled(false);
        textFieldNoOfAntiflue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfAntiflueActionPerformed(evt);
            }
        });

        textMedResponseText.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textMedResponseText.setForeground(new java.awt.Color(83, 81, 85));
        textMedResponseText.setEnabled(false);
        textMedResponseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMedResponseTextActionPerformed(evt);
            }
        });

        textFieldNoOfAntibiotics.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfAntibiotics.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfAntibiotics.setEnabled(false);
        textFieldNoOfAntibiotics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfAntibioticsActionPerformed(evt);
            }
        });

        textFieldNoOfAntiseptics.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfAntiseptics.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfAntiseptics.setEnabled(false);
        textFieldNoOfAntiseptics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfAntisepticsActionPerformed(evt);
            }
        });

        textFieldNoOfShirtsL.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfShirtsL.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfShirtsL.setEnabled(false);
        textFieldNoOfShirtsL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfShirtsLActionPerformed(evt);
            }
        });

        textFieldNoOfShirtsS.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfShirtsS.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfShirtsS.setEnabled(false);
        textFieldNoOfShirtsS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfShirtsSActionPerformed(evt);
            }
        });

        textFieldNoOfPantsS.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfPantsS.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfPantsS.setEnabled(false);
        textFieldNoOfPantsS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfPantsSActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(148, 150, 149));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("No. of Shirt (L):");

        textFieldNoOfPantsM.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfPantsM.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfPantsM.setEnabled(false);
        textFieldNoOfPantsM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfPantsMActionPerformed(evt);
            }
        });

        textFieldNoOfShirtsM.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfShirtsM.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfShirtsM.setEnabled(false);
        textFieldNoOfShirtsM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfShirtsMActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(148, 150, 149));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("No. of Shirt (S):");

        jLabel11.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(148, 150, 149));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("No. of Shirt (M):");

        jLabel12.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(148, 150, 149));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("No. of Pants (S):");

        jLabel13.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(148, 150, 149));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("No. of Pants (M):");

        jLabel14.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(148, 150, 149));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Clothes List:");

        jLabel15.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(148, 150, 149));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("No. of Pants (L):");

        textFieldNoOfPantsL.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfPantsL.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfPantsL.setEnabled(false);
        textFieldNoOfPantsL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfPantsLActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(148, 150, 149));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("No. of People:");

        textFieldNoOfAntipyretics.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfAntipyretics.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfAntipyretics.setEnabled(false);
        textFieldNoOfAntipyretics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfAntipyreticsActionPerformed(evt);
            }
        });

        btnMedReject.setBackground(new java.awt.Color(255, 255, 255));
        btnMedReject.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnMedReject.setForeground(new java.awt.Color(83, 81, 85));
        btnMedReject.setText("Reject");
        btnMedReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedRejectActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(148, 150, 149));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Medicine Response:");

        jLabel18.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(148, 150, 149));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Clothes Response:");

        btnClothesApprove.setBackground(new java.awt.Color(255, 255, 255));
        btnClothesApprove.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnClothesApprove.setForeground(new java.awt.Color(83, 81, 85));
        btnClothesApprove.setText("Accept");
        btnClothesApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClothesApproveActionPerformed(evt);
            }
        });

        btnClothesReject.setBackground(new java.awt.Color(255, 255, 255));
        btnClothesReject.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnClothesReject.setForeground(new java.awt.Color(83, 81, 85));
        btnClothesReject.setText("Reject");
        btnClothesReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClothesRejectActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(83, 81, 85));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(148, 150, 149));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Work ID:");

        textWorkID.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textWorkID.setForeground(new java.awt.Color(83, 81, 85));
        textWorkID.setEnabled(false);
        textWorkID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textWorkIDActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(148, 150, 149));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Status:");

        jLabel21.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(148, 150, 149));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Status:");

        textFieldNoOfPeople.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfPeople.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfPeople.setEnabled(false);
        textFieldNoOfPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfPeopleActionPerformed(evt);
            }
        });

        textClothesResponseText.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textClothesResponseText.setForeground(new java.awt.Color(83, 81, 85));
        textClothesResponseText.setEnabled(false);
        textClothesResponseText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textClothesResponseTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldNoOfShirtsM, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNoOfShirtsL, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNoOfPantsS, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNoOfPantsM, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNoOfPantsL, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(textFieldNoOfPeople))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(textFieldNoOfAnalgesics)
                                                    .addComponent(textFieldNoOfAntiflue)
                                                    .addComponent(textFieldNoOfAntibiotics)
                                                    .addComponent(textFieldNoOfAntiseptics, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                                    .addComponent(textFieldNoOfAntipyretics))))
                                        .addGap(56, 56, 56)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textWorkID, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textFieldNoOfShirtsS, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(110, 110, 110))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(btnMedApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMedReject, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(btnClothesApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClothesReject, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textClothesResponseText)
                            .addComponent(textMedResponseText, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19)
                    .addComponent(textWorkID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNoOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textFieldNoOfAntipyretics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textFieldNoOfAnalgesics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textFieldNoOfAntiflue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textFieldNoOfAntibiotics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textFieldNoOfAntiseptics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(textFieldNoOfShirtsS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldNoOfShirtsM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldNoOfShirtsL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldNoOfPantsS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldNoOfPantsM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldNoOfPantsL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMedReject)
                    .addComponent(jLabel17)
                    .addComponent(btnMedApprove)
                    .addComponent(jLabel20)
                    .addComponent(textMedResponseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClothesApprove)
                    .addComponent(btnClothesReject)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21)
                    .addComponent(textClothesResponseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNoOfAnalgesicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfAnalgesicsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfAnalgesicsActionPerformed

    private void btnMedApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedApproveActionPerformed
        // TODO add your handling code here:
        work.setFiduciaryMedDescission("",neuServeUp.getuUser(),true);
        setMedicalButtons(false);
        setValuesInFields();
        JOptionPane.showMessageDialog(null, "Response recorded");
    }//GEN-LAST:event_btnMedApproveActionPerformed

    private void textFieldNoOfAntiflueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfAntiflueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfAntiflueActionPerformed

    private void textMedResponseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMedResponseTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMedResponseTextActionPerformed

    private void textFieldNoOfAntibioticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfAntibioticsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfAntibioticsActionPerformed

    private void textFieldNoOfAntisepticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfAntisepticsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfAntisepticsActionPerformed

    private void textFieldNoOfShirtsLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfShirtsLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfShirtsLActionPerformed

    private void textFieldNoOfShirtsSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfShirtsSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfShirtsSActionPerformed

    private void textFieldNoOfPantsSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfPantsSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfPantsSActionPerformed

    private void textFieldNoOfPantsMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfPantsMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfPantsMActionPerformed

    private void textFieldNoOfShirtsMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfShirtsMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfShirtsMActionPerformed

    private void textFieldNoOfPantsLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfPantsLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfPantsLActionPerformed

    private void textFieldNoOfAntipyreticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfAntipyreticsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfAntipyreticsActionPerformed

    private void btnMedRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedRejectActionPerformed
        // TODO add your handling code here:
        work.setFiduciaryMedDescission("",neuServeUp.getuUser(),false);
        setMedicalButtons(false);
        setValuesInFields();
        JOptionPane.showMessageDialog(null, "Response recorded");
    }//GEN-LAST:event_btnMedRejectActionPerformed

    private void btnClothesApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClothesApproveActionPerformed
        // TODO add your handling code here:
        work.setFiduciaryClothesDescission("",neuServeUp.getuUser(),true);
        setClothesButtons(false);
        setValuesInFields();
        JOptionPane.showMessageDialog(null, "Response recorded");
    }//GEN-LAST:event_btnClothesApproveActionPerformed

    private void btnClothesRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClothesRejectActionPerformed
        // TODO add your handling code here:
        work.setFiduciaryClothesDescission("",neuServeUp.getuUser(),false);
        setClothesButtons(false);
        setValuesInFields();
        JOptionPane.showMessageDialog(null, "Response recorded");
    }//GEN-LAST:event_btnClothesRejectActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        toPreviousScreen();
    }//GEN-LAST:event_btnBackActionPerformed

    private void textWorkIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textWorkIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textWorkIDActionPerformed

    private void textFieldNoOfPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfPeopleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfPeopleActionPerformed

    private void textClothesResponseTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textClothesResponseTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textClothesResponseTextActionPerformed

    public void toPreviousScreen(){
        CardLayout layout = (CardLayout)this.neuServeUp.getPanelBody().getLayout();
        neuServeUp.getPanelBody().remove(this);
        Component[] comps =  neuServeUp.getPanelBody().getComponents();
        for(Component comp:comps){
            if(comp instanceof FiduciaryDashboard){
                FiduciaryDashboard panel = (FiduciaryDashboard)comp;
                panel.populateAllTables();
            }
        }
        layout.previous(neuServeUp.getPanelBody());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClothesApprove;
    private javax.swing.JButton btnClothesReject;
    private javax.swing.JButton btnMedApprove;
    private javax.swing.JButton btnMedReject;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textClothesResponseText;
    private javax.swing.JTextField textFieldNoOfAnalgesics;
    private javax.swing.JTextField textFieldNoOfAntibiotics;
    private javax.swing.JTextField textFieldNoOfAntiflue;
    private javax.swing.JTextField textFieldNoOfAntipyretics;
    private javax.swing.JTextField textFieldNoOfAntiseptics;
    private javax.swing.JTextField textFieldNoOfPantsL;
    private javax.swing.JTextField textFieldNoOfPantsM;
    private javax.swing.JTextField textFieldNoOfPantsS;
    private javax.swing.JTextField textFieldNoOfPeople;
    private javax.swing.JTextField textFieldNoOfShirtsL;
    private javax.swing.JTextField textFieldNoOfShirtsM;
    private javax.swing.JTextField textFieldNoOfShirtsS;
    private javax.swing.JTextField textMedResponseText;
    private javax.swing.JTextField textWorkID;
    // End of variables declaration//GEN-END:variables
}
