/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.survey;
import Business.NEUServeUp;
import Business.Util.Helper;
import Business.Work.MedicalWorkRequest;
import Business.Work.ClothesWorkRequest;
import Business.Work.Work;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Aishwarya
 */
public class CreateRequest extends javax.swing.JPanel {

    /**
     * Creates new form CreateRequest
     */
    MedicalWorkRequest medicalWorkRequest;
    ClothesWorkRequest clothesWorkRequest;
    NEUServeUp neuServeUp;
   
    public CreateRequest() {
        initComponents();
        neuServeUp = NEUServeUp.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldNoOfAnalgesics = new javax.swing.JTextField();
        btnGenerateRequest = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textFieldNoOfAntiflue = new javax.swing.JTextField();
        textFieldNoOfPeople = new javax.swing.JTextField();
        textFieldNoOfAntibiotics = new javax.swing.JTextField();
        textFieldNoOfAntiseptics = new javax.swing.JTextField();
        textFieldNoOfShirtsL = new javax.swing.JTextField();
        textFieldNoOfShirtsS = new javax.swing.JTextField();
        textFieldNoOfPantsS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textFieldNoOfPantsM = new javax.swing.JTextField();
        textFieldNoOfShirtsM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        textFieldNoOfPantsL = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textFieldNoOfAntipyretics = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(38, 54, 68));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel2.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(148, 150, 149));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Medicine List:");

        jLabel3.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(148, 150, 149));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("CREATE REQUEST");

        jLabel4.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(148, 150, 149));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("No. of Antiflue:");

        textFieldNoOfAnalgesics.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfAnalgesics.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfAnalgesics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfAnalgesicsActionPerformed(evt);
            }
        });

        btnGenerateRequest.setBackground(new java.awt.Color(255, 255, 255));
        btnGenerateRequest.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnGenerateRequest.setForeground(new java.awt.Color(83, 81, 85));
        btnGenerateRequest.setText("Generate Request");
        btnGenerateRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateRequestActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(148, 150, 149));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("No. of Antipyretics:");

        jLabel6.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(148, 150, 149));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("No. of Analgesics:");

        jLabel7.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(148, 150, 149));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("No. of Antibiotics:");

        jLabel8.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(148, 150, 149));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("No. of Antiseptics:");

        textFieldNoOfAntiflue.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfAntiflue.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfAntiflue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfAntiflueActionPerformed(evt);
            }
        });

        textFieldNoOfPeople.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfPeople.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfPeopleActionPerformed(evt);
            }
        });

        textFieldNoOfAntibiotics.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfAntibiotics.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfAntibiotics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfAntibioticsActionPerformed(evt);
            }
        });

        textFieldNoOfAntiseptics.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfAntiseptics.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfAntiseptics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfAntisepticsActionPerformed(evt);
            }
        });

        textFieldNoOfShirtsL.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfShirtsL.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfShirtsL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfShirtsLActionPerformed(evt);
            }
        });

        textFieldNoOfShirtsS.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfShirtsS.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfShirtsS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfShirtsSActionPerformed(evt);
            }
        });

        textFieldNoOfPantsS.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfPantsS.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfPantsS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfPantsSActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(148, 150, 149));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("No. of Shirt (L):");

        textFieldNoOfPantsM.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfPantsM.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfPantsM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfPantsMActionPerformed(evt);
            }
        });

        textFieldNoOfShirtsM.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfShirtsM.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfShirtsM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfShirtsMActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(148, 150, 149));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("No. of Shirt (S):");

        jLabel11.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(148, 150, 149));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("No. of Shirt (M):");

        jLabel12.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(148, 150, 149));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("No. of Pants (S):");

        jLabel13.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(148, 150, 149));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("No. of Pants (M):");

        jLabel14.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(148, 150, 149));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Clothes List:");

        jLabel15.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(148, 150, 149));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("No. of Pants (L):");

        textFieldNoOfPantsL.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfPantsL.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfPantsL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfPantsLActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(148, 150, 149));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("No. of People:");

        textFieldNoOfAntipyretics.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        textFieldNoOfAntipyretics.setForeground(new java.awt.Color(83, 81, 85));
        textFieldNoOfAntipyretics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNoOfAntipyreticsActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(83, 81, 85));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNoOfPeople, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textFieldNoOfAnalgesics)
                                        .addComponent(textFieldNoOfAntiflue)
                                        .addComponent(textFieldNoOfAntibiotics, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                        .addComponent(textFieldNoOfAntiseptics, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                        .addComponent(textFieldNoOfAntipyretics)))))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldNoOfShirtsM, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNoOfShirtsS, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNoOfShirtsL, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNoOfPantsS, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNoOfPantsM, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNoOfPantsL, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGenerateRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(221, 221, 221))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(textFieldNoOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel14))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textFieldNoOfAntipyretics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textFieldNoOfAnalgesics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textFieldNoOfAntiflue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textFieldNoOfAntibiotics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textFieldNoOfAntiseptics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(textFieldNoOfShirtsS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldNoOfShirtsM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldNoOfShirtsL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldNoOfPantsS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldNoOfPantsM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldNoOfPantsL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerateRequest)
                    .addComponent(btnCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNoOfAnalgesicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfAnalgesicsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfAnalgesicsActionPerformed

    private void btnGenerateRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateRequestActionPerformed
        // TODO add your handling code here:
        Helper helper= new Helper();
        if(!helper.isValidQuantity(textFieldNoOfPeople.getText()) ){
            JOptionPane.showMessageDialog(null, "Please enter valid People count");
            return;
        }
        if(Integer.parseInt(textFieldNoOfPeople.getText()) == 0){
            JOptionPane.showMessageDialog(null, "People count can't be zero");
            return;
        }
        if(!helper.isValidQuantity(textFieldNoOfAnalgesics.getText() )){
            JOptionPane.showMessageDialog(null, "Please enter valid Analgesics count");
            return;
        }
        if(!helper.isValidQuantity(textFieldNoOfAntibiotics.getText())){
            JOptionPane.showMessageDialog(null, "Please enter valid Antibiotics count");
            return;
        }
        if(!helper.isValidQuantity(textFieldNoOfAntiflue.getText())){
            JOptionPane.showMessageDialog(null, "Please enter valid Antiflue count");
            return;
        }
        if(!helper.isValidQuantity(textFieldNoOfAntipyretics.getText())){
            JOptionPane.showMessageDialog(null, "Please enter valid ntipyretics count");
            return;
        }
        if(!helper.isValidQuantity(textFieldNoOfAntiseptics.getText())){
            JOptionPane.showMessageDialog(null, "Please enter valid Antiseptics count");
            return;
        }
        if(!helper.isValidQuantity(textFieldNoOfPantsL.getText())){
            JOptionPane.showMessageDialog(null, "Please enter valid Pants(L) count");
            return;
        }
        if(!helper.isValidQuantity(textFieldNoOfPantsM.getText())){
            JOptionPane.showMessageDialog(null, "Please enter valid Pants(M) count");
            return;
        }
         if(!helper.isValidQuantity(textFieldNoOfPantsS.getText())){
            JOptionPane.showMessageDialog(null, "Please enter valid Pants(S) count");
            return;
        }
        if(!helper.isValidQuantity(textFieldNoOfShirtsS.getText())){
            JOptionPane.showMessageDialog(null, "Please enter valid Shirts(S) count");
            return;
        }
        if(!helper.isValidQuantity(textFieldNoOfShirtsM.getText())){
            JOptionPane.showMessageDialog(null, "Please enter valid Shirts(M) count");
            return;
        }
        if(!helper.isValidQuantity(textFieldNoOfShirtsL.getText())){
            JOptionPane.showMessageDialog(null, "Please enter valid Shirts(L) count");
            return;
        }
        
        ClothesWorkRequest clothesWorkRequest = new ClothesWorkRequest();
        MedicalWorkRequest medicalWorkRequest = new MedicalWorkRequest();
     
        clothesWorkRequest.setNumberOfSmallShirts(Integer.parseInt(textFieldNoOfShirtsS.getText()));
        clothesWorkRequest.setNumberOfMediumShirts(Integer.parseInt(textFieldNoOfShirtsM.getText()));
        clothesWorkRequest.setNumberOfLargeShirts(Integer.parseInt(textFieldNoOfShirtsL.getText()));
        clothesWorkRequest.setNumberOfSmallPants(Integer.parseInt(textFieldNoOfPantsS.getText()));
        clothesWorkRequest.setNumberOfMediumPants(Integer.parseInt(textFieldNoOfPantsM.getText()));
        clothesWorkRequest.setNumberOfLargePants(Integer.parseInt(textFieldNoOfPantsL.getText()));
       
        medicalWorkRequest.setNumberOfAntipyretics(Integer.parseInt(textFieldNoOfAntipyretics.getText()));
        medicalWorkRequest.setNumberOfAnalgesics(Integer.parseInt(textFieldNoOfAnalgesics.getText()));
        medicalWorkRequest.setNumberOfAntiFlue(Integer.parseInt(textFieldNoOfAntiflue.getText()));
        medicalWorkRequest.setNumberOfAntibiotics(Integer.parseInt(textFieldNoOfAntibiotics.getText()));
        medicalWorkRequest.setNumberOfAntiseptics(Integer.parseInt(textFieldNoOfAntiseptics.getText()));
        
        neuServeUp.getWorkDirectory().createNewWork(Integer.parseInt(textFieldNoOfPeople.getText()), clothesWorkRequest, medicalWorkRequest);
        JOptionPane.showMessageDialog(null, "Work created successfully.");
        toPreviousScreen();
    }//GEN-LAST:event_btnGenerateRequestActionPerformed

    private void textFieldNoOfAntiflueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfAntiflueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfAntiflueActionPerformed

    private void textFieldNoOfAntibioticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfAntibioticsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfAntibioticsActionPerformed

    private void textFieldNoOfAntisepticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfAntisepticsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfAntisepticsActionPerformed

    private void textFieldNoOfShirtsLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfShirtsLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfShirtsLActionPerformed

    private void textFieldNoOfShirtsSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfShirtsSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfShirtsSActionPerformed

    private void textFieldNoOfPantsSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfPantsSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfPantsSActionPerformed

    private void textFieldNoOfPantsMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfPantsMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfPantsMActionPerformed

    private void textFieldNoOfShirtsMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfShirtsMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfShirtsMActionPerformed

    private void textFieldNoOfPantsLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfPantsLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfPantsLActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        toPreviousScreen();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void textFieldNoOfAntipyreticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfAntipyreticsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfAntipyreticsActionPerformed

    private void textFieldNoOfPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNoOfPeopleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNoOfPeopleActionPerformed
    public void toPreviousScreen(){
        CardLayout layout = (CardLayout)this.neuServeUp.getPanelBody().getLayout();
        neuServeUp.getPanelBody().remove(this);
        Component[] comps =  neuServeUp.getPanelBody().getComponents();
        for(Component comp:comps){
            if(comp instanceof SurveyDashboard){
                SurveyDashboard panel = (SurveyDashboard)comp;
                panel.populateSurveyTable();
            }
        }
        layout.previous(neuServeUp.getPanelBody());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGenerateRequest;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textFieldNoOfAnalgesics;
    private javax.swing.JTextField textFieldNoOfAntibiotics;
    private javax.swing.JTextField textFieldNoOfAntiflue;
    private javax.swing.JTextField textFieldNoOfAntipyretics;
    private javax.swing.JTextField textFieldNoOfAntiseptics;
    private javax.swing.JTextField textFieldNoOfPantsL;
    private javax.swing.JTextField textFieldNoOfPantsM;
    private javax.swing.JTextField textFieldNoOfPantsS;
    private javax.swing.JTextField textFieldNoOfPeople;
    private javax.swing.JTextField textFieldNoOfShirtsL;
    private javax.swing.JTextField textFieldNoOfShirtsM;
    private javax.swing.JTextField textFieldNoOfShirtsS;
    // End of variables declaration//GEN-END:variables
}
