/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.survey;

import Business.NEUServeUp;
import Business.Util.Helper;
import Business.Work.Work;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rwalawalkar
 */
public class SurveyDashboard extends javax.swing.JPanel {

    public NEUServeUp neuServeUp;
    /**
     * Creates new form SurveyDashboard
     */
    public SurveyDashboard() {
        initComponents();
        neuServeUp = NEUServeUp.getInstance();
        populateSurveyTable();
    }
    
    public void populateSurveyTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblSurvey.getModel();
        dtm.setRowCount(0);
        Helper helper = new Helper();
        
        for(Work work : neuServeUp.getWorkDirectory().getWorkListLastestFirstOrder()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]=work;
            row[1]= work.getNumberOfPeople();
            row[2]= helper.dateToString(work.getCreatedOn());
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnCreateTask = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSurvey = new javax.swing.JTable();

        setBackground(new java.awt.Color(38, 54, 68));

        jLabel3.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(148, 150, 149));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("SURVEY");

        btnCreateTask.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateTask.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        btnCreateTask.setForeground(new java.awt.Color(83, 81, 85));
        btnCreateTask.setText("Create Work");
        btnCreateTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTaskActionPerformed(evt);
            }
        });

        tblSurvey.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        tblSurvey.setFont(new java.awt.Font("Monaco", 0, 12)); // NOI18N
        tblSurvey.setForeground(new java.awt.Color(83, 81, 85));
        tblSurvey.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Work ID", "No of People", "Created On"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSurvey.setGridColor(new java.awt.Color(83, 81, 85));
        tblSurvey.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tblSurvey);
        if (tblSurvey.getColumnModel().getColumnCount() > 0) {
            tblSurvey.getColumnModel().getColumn(0).setResizable(false);
            tblSurvey.getColumnModel().getColumn(1).setResizable(false);
            tblSurvey.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCreateTask, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTaskActionPerformed
        // TODO add your handling code here:
        
        CreateRequest createRequest= new CreateRequest();
        neuServeUp.getPanelBody().add("CreateRequest", createRequest);
        CardLayout layout = (CardLayout) neuServeUp.getPanelBody().getLayout();
        layout.next(neuServeUp.getPanelBody());
    }//GEN-LAST:event_btnCreateTaskActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateTask;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSurvey;
    // End of variables declaration//GEN-END:variables
}
